class KtextString {
  KtextString._();
  static const String onBordingTitle1 = "Real-time Global Market Quotes.";
  static const String onBordingTitle2 = "Expand Your Stock Portflio.";
  static const String onBordingTitle3 = "Access Smart Trading Tools.";

  static const String onBordingSubTitle1 =
      "Get live stock market quotes,charts, detailed company profiles.";
  static const String onBordingSubTitle2 =
      "Invest companies and ETFs without purchasing a whole share.";
  static const String onBordingSubTitle3 =
      "Over 50 technical indicators and 12 charting tools.";

  static const String onBrodingImg1 =
      "Assets/images/onbording_img/onbording_1.png";
  static const String onBrodingImg2 =
      "Assets/images/onbording_img/onbording_2.png";
  static const String onBrodingImg3 =
      "Assets/images/onbording_img/onbording_3.png";

  static const String homeAppBarTitle = 'Good day!!';
  static const String homeAppBarSubTitle = 'Harshil Patel';

  static const String emailV = 'Verify your email address!';
  static const String emailVerifyDis =
      'Congratulations! Your Account Awaits: Varify Your Email to Start Trading';

  static const String sucssessFullT = 'Your account sucssessfully created!';
  static const String sucssessFullDis =
      'Welcome! In this app you can see trading chart and use various indicator tools';

  static const String fPasswordTitle = 'Forget Password';
  static const String fPasswordSubTitle =
      'Don\'t worry sometimes pepole can forget too, enter your email and we will send you a password reser link. ';

  static const String emailResetTitle = 'Password Reset Email Sent';
  static const String emailResetSubTitle =
      'Your Account Security is Our Priority! We\'ve sent You a Secure Link to Safely Change Your Password and keep your Account Protected.';

  static const String searchBarText = 'Search Here!';

  static const String passwordRule =
      'Your reset password must contain one numeric value and one spacial character.';

  static const String privacyDate = 'Last updated: April 29, 2024';
  static const String privacyDis =
      'This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.';
  static const String privacyDis1 =
      'We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.';
  static const String heading = 'Interpretation and Definitions';
  static const String subHeading = 'Interpretation';
  static const String privacyDis2 =
      'The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.';
  static const String subHeading1 = 'Definitions';
  static const String privacyDis3 = 'For the purposes of this Privacy Policy:';
  static const String privacyDis4 =
      'Account means a unique account created for You to access our Service or parts of our Service.';
  static const String privacyDis5 =
      'Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.';
  static const String privacyDis6 =
      'Application refers to Trade Analyze, the software program provided by the Company.';
  static const String privacyDis7 =
      'Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Trade Analyze.';
  static const String privacyDis8 = 'Country refers to: Gujarat, india';
  static const String privacyDis9 =
      'Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.';
  static const String privacyDis10 =
      'Personal Data is any information that relates to an identified or identifiable individual.';
  static const String privacyDis11 = 'Service refers to the Application.';
  static const String privacyDis12 =
      'Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.';
  static const String privacyDis13 =
      'Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit';

  static const String privacyDis14 =
      'You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.';
  static const String heading1 = 'Collecting and Using Your Personal Data';
  static const String subHeading2 = 'Personal Data';
  static const String privacyDis15 =
      'While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:';
  static const String boltD = 'Email address';
  static const String boltD1 = 'First name and last name';
  static const String boltD2 = 'Phone number';
  static const String boltD3 = 'Usage Data';
  static const String heading2 = 'Contact Us';
  static const String privacyDis16 =
      'If you have any questions about this Privacy Policy, You can contact us:';
  static const String boltD4 = 'By email: hplion299@gmail.com';
}

// https://www.termsfeed.com/live/c3c9747c-58a4-4bc3-984d-1eac04a3e99b
